import json
from typing import List

import httpx

from ..models import CandidateRecord, ConversationTurn, EngagementResult, ParsedJD


OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_MODEL = "mistral"


def _fallback_assess_interest(candidate: CandidateRecord, jd: ParsedJD) -> EngagementResult:
    text = candidate.profile_text.lower()
    match_terms = ["interested", "open to work", "actively looking", "career growth", "excited"]
    stable_terms = ["not looking", "happy in current role", "do not contact"]

    plus = sum(1 for t in match_terms if t in text)
    minus = sum(1 for t in stable_terms if t in text)

    base = 55
    score = max(10, min(95, base + (plus * 8) - (minus * 15)))

    conv = [
        ConversationTurn(role="agent", message=f"Hi {candidate.name}, we found a potential fit for {jd.title}. Would you consider exploring it?"),
        ConversationTurn(
            role="candidate",
            message=(
                "I am open to hearing more about high-impact roles."
                if score >= 65
                else "I may consider it depending on role scope and flexibility."
            ),
        ),
        ConversationTurn(role="agent", message="What would make this opportunity compelling for you?"),
        ConversationTurn(
            role="candidate",
            message=(
                "Growth, ownership, and a strong engineering culture are important to me."
                if score >= 65
                else "Compensation, team quality, and role clarity matter most."
            ),
        ),
    ]

    rationale = "High intent signals in profile summary." if score >= 65 else "Neutral intent; needs stronger value proposition."

    return EngagementResult(
        candidate_id=candidate.candidate_id,
        interest_score=round(float(score), 2),
        rationale=rationale,
        conversation=conv,
    )


async def _ollama_assess_interest(candidate: CandidateRecord, jd: ParsedJD) -> EngagementResult:
    prompt = f"""
You are simulating recruiter outreach with a candidate.
Job title: {jd.title}
Job summary: {jd.summary}
Candidate name: {candidate.name}
Candidate profile: {candidate.profile_text}

Return STRICT JSON with keys:
- interest_score (0-100 number)
- rationale (short string)
- conversation (list of 4 objects with role and message)
""".strip()

    async with httpx.AsyncClient(timeout=25) as client:
        response = await client.post(
            OLLAMA_URL,
            json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False},
        )
        response.raise_for_status()
        body = response.json().get("response", "").strip()

    parsed = json.loads(body)
    conv = [ConversationTurn(**t) for t in parsed.get("conversation", [])]

    return EngagementResult(
        candidate_id=candidate.candidate_id,
        interest_score=round(float(parsed.get("interest_score", 50)), 2),
        rationale=parsed.get("rationale", "Generated by local model."),
        conversation=conv,
    )


async def assess_interest(candidate: CandidateRecord, jd: ParsedJD) -> EngagementResult:
    try:
        return await _ollama_assess_interest(candidate, jd)
    except Exception:
        return _fallback_assess_interest(candidate, jd)


async def batch_assess_interest(candidates: List[CandidateRecord], jd: ParsedJD) -> List[EngagementResult]:
    results: List[EngagementResult] = []
    for candidate in candidates:
        results.append(await assess_interest(candidate, jd))
    return results
